### ISSUE TITLE
안녕하세요, RL 관련 글들 홈페이지 호스팅 문의

### ISSUE THREAD

**Issue by Jinoh-Cho** [HeekangPark/HeekangPark.github.io#5]
안녕하세요, 강화학습을 공부하고 있는 학생입니다.

기존에 강화학습을 공부할 때 RL 관련 정리 글이 잘 되있던 것 같아서, 다시 보러 왔는데 홈페이지가 업데이트 되어 볼 수가 없는 상황입니다.

혹시 가능하다면 해당 자료들을 홈페이지에 호스팅 가능하도록 변경 가능할까요? 감사합니다.

**Comment by HeekangPark** [comment]
안녕하세요. 현재 홈페이지 개편 작업으로 인해 이전 문서들을 호스팅할 수 없는 상태입니다. 최대한 빠르게 이전을 완료할 예정이니 조금만 기다려 주세요.

다만 <https://github.com/HeekangPark/HeekangPark.github.io/tree/master/docs/.old> 디렉토리에서 markdown 포멧(kramdown)으로 이전 문서들을 참조하실 수 있습니다.

**Comment by HeekangPark** [comment]
안녕하세요. RL 관련 글 모두 복구했습니다. 감사합니다.
